name: first_pipeline

on:
  push: 
    branches:  
       - main

jobs:
  hellojob:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout Code
           uses: actions/checkout@v4

         -  name: Print message
            run:  echo "Hello TUSHAR bhai!! pipeline chal gayiii! " 

         - name: show files
           run: ls -la

         - name: show current directory
           run: pwd
         - name: Done bhai
           run: echo "mubarrak hoo bhai sab ek no. chal gaya! " 
       
