name: first_pipeline

on:
  push: 
    branches:  
       - main

jobs:
  hellojob:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout Code
           uses: actions/checkout@v4

         -  name: Print message
            run:  echo "Hello TUSHAR bhai!! pipeline chal gayiii! " 
       
